image: java:8-jdk

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - analyze
  - publish

cache:
  group: swagger_confluence
  key: "$CI_BUILD_REF_NAME"
  paths:
     - .gradle/wrapper
     - .gradle/caches

job_build:
  stage: build
  script:
    - ./gradlew clean build shadowJar
  except:
    - maseter
  tags:
    - docker

job_build_master:
  stage: build
  script:
    - ./gradlew clean build shadowJar -Prelease=true
  only:
    - master
  tags:
    - docker

job_analyze_develop:
  stage: analyze
  script:
    - ./gradlew jacocoTestReport sonarqube -Dsonar.issuesReport.console.enable=true -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref=$CI_BUILD_REF_NAME
  only:
    - develop
  tags:
    - docker

job_analyze_pull:
  stage: analyze
  script:
    - ./gradlew jacocoTestReport sonarqube -Dsonar.analysis.mode=preview -Dsonar.issuesReport.console.enable=true -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref=$CI_BUILD_REF_NAME
  except:
    - develop
    - master
  tags:
    - docker

job_publish_develop:
  stage: publish
  only:
    - develop
  script:
    - ./gradlew publish
  artifacts:
    paths:
    - swagger-confluence-cli/build/libs/*.jar
    - swagger-confluence-core/build/libs/*.jar
    - swagger-confluence-gradle-plugin/build/libs/*.jar
  tags:
    - docker

job_publish_master:
  stage: publish
  only:
    - master
  script:
    - ./gradlew publish -Prelease=true
  artifacts:
    paths:
    - swagger-confluence-cli/build/libs/*.jar
    - swagger-confluence-core/build/libs/*.jar
    - swagger-confluence-gradle-plugin/build/libs/*.jar
  tags:
    - docker